[package]
name = "disk-types"
version = "0.1.5"
authors = ["Jeremy Soller <jackpot51@gmail.com>", "Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "Common traits and types for handling block devices, partitions, file systems, etc."
keywords =  ["disk", "partition"]
categories = ["filesystem", "os"]
edition = "2018"

[dependencies]
sys-mount = "3.1.0"
tempdir = "0.3.7"
os-detect = { path = "../os-detect" }
sysfs-class = "0.1.3"
libparted = "0.1.5"
log = "0.4"
thiserror = "2.0.20"
