[package]
name = "distinst"
version = "0.5.0"
description = "Distribution Installer Backend"
repository = "https://github.com/pop-os/distinst"
categories = ["os::unix-apis"]
keywords = ["linux", "distribution", "installer"]
authors = [
    "Jeremy Soller <jackpot51@gmail.com>",
    "Michael Aaron Murphy <michael@system76.com>"
]
license = "LGPL-3.0"
readme = "README.md"
edition = "2018"

[workspace]
members = [
    "cli",
    "crates/*",
    "ffi",
]

[lib]
name = "distinst"
crate-type = ["lib"]

[dev-dependencies]
pbr = "1.1.1"

[dependencies]
cascade = "1.0"
dirs = "6.0"
disk-types = { path = "crates/disk-types"}
distinst-bootloader = { path = "crates/bootloader" }
distinst-chroot = { path = "crates/chroot" }
distinst-disks = { path = "crates/disks" }
distinst-external-commands = { path = "crates/external" }
distinst-hardware-support = { path = "crates/hardware" }
distinst-locale-support = { path = "crates/locales" }
distinst-squashfs = { path = "crates/squashfs" }
distinst-timezones = { path = "crates/timezones" }
distinst-utils = { path = "crates/utils" }
envfile = "0.2.1"
fern = "0.7.1"
fomat-macros = "0.3"
fstab-generate = { path = "crates/fstab-generate" }
hostname-validator = "1.1.1"
itertools = "0.15.0"
libc = "0.2.189"
libparted = "0.1.5"
log = "0.4.34"
logind-dbus = "0.1.1"
os-detect = { path = "crates/os-detect" }
os-release = "0.1.0"
partition-identity = "0.3.1"
proc-mounts = "0.3.0"
rayon = "1.12.0"
sys-mount = "3.1.0"
tempdir = "0.3.7"
bitflags = "2.13.1"
apt-cli-wrappers = { git = "https://github.com/pop-os/apt-cli-wrappers" }
systemd-boot-conf = "0.2.2"
derive_more = { version = "2.1.1", features = ["full"] }
anyhow = "1.0.104"
bstr = "1.13.1"
thiserror = "2.0.20"

[profile.release]
debug = true
