[package]
name = "distinst_cli"
version = "0.4.0"
description = "Distribution Installer Backend"
repository = "https://github.com/pop-os/distinst"
authors = [
    "Jeremy Soller <jackpot51@gmail.com>",
    "Michael Aaron Murphy <michael@system76.com>"
]
license = "LGPL-3.0"
readme = "README.md"
edition = "2018"

[[bin]]
name = "distinst"
path = "src/main.rs"

[dependencies]
clap = "2.33.0"
dbus = "0.9.12"
distinst = { path = ".." }
libc = "0.2.189"
pbr = "1.1.1"
partition-identity = "0.3.1"
proc-mounts = "0.3.0"
thiserror = "2.0.20"
